[Default]
# 数据库驱动
driver = "sqlite"

# 名称
cluster_name = "Default"

# 设置最大的并发打开连接数
max_open_conns = 24
# 设置最大的空闲连接数
max_idle_conns = 0
# 设置连接的最大生命周期，毫秒级
conn_max_lifetime_ms = 18000

# 负载均衡选择器，留空表示使用默认的随机选择器
balance_strategy = ""

# 编码，名称说明参见mysql手册
charset = "utf8mb4"

# 登录MySql的用户名和密码
username = "xxxxx"
password = "xxxxxxx"

# 默认数据库，必填
default_db  = "yawebapp"

#主机信息数组，逗号分割
hosts = "127.0.0.1:3306"